apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: data-europeana-gateway
build:
  artifacts:
  - image: europeana/api-gateway
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/cluster-ip-service.yaml
    - k8s/config.properties.yaml.template
    - k8s/deployment.yaml
    - k8s/ingress.yaml.template
    - k8s/node-port.yaml
