apiVersion: v1
kind: Service
metadata:
  name: data-europeana-gateway-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: data-europeana-gateway
  ports:
    - port: 80
      targetPort: 80