apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-europeana-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-europeana-gateway
  template:
    metadata:
      labels:
        app: data-europeana-gateway
    spec:
      containers:
        - name: data-europeana-gateway
          image: data-europeana-gateway
#          image: europeana/data-europeana-gateway
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: data-europeana-gateway-config
