apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-gateway-deployment
spec:
# selector.matchLabels provided via Kustomize
  template:
    spec:
      containers:
        - name: data-gateway
          image: europeana/data-gateway
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              port: 80
              path: /nginx-health
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 80
              path: /nginx-health
            initialDelaySeconds: 5
            periodSeconds: 5
          envFrom:
            - configMapRef:
                name: data-gateway-config

