# NodePort service for accessing API locally. Use ingress for IBM cloud deployments
# API can be accessed on http://<cluster-ip>:31000
# For Docker Desktop, cluster-ip is "localhost";
# if using Minikube, run "minikube ip" to get IP address of your cluster
apiVersion: v1
kind: Service
metadata:
  name: data-service
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 31000
  selector:
    app: data-gateway